name: Deploy React Frontend to S3

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "22" # Specify the Node.js version you want to use

      - name: Reload the source
        run: source ~/.bashrc

      - name: Install dependencies
        run: npm install

      - name: Set up Firebase environment variables
        run: |
          echo "VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }}" >> .env
          echo "VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }}" >> .env
          echo "VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }}" >> .env
          echo "VITE_FIREBASE_MESSAGING_SENDER_ID=${{secrets.VITE_FIREBASE_MESSAGING_SENDER_ID}}" >> .env

      - name: Build the project
        run: npm run build

      - name: Sync S3 bucket
        run: |
          pwd
          sudo snap install aws-cli
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
