name: Deploy React Frontend to EC2

on:
  push:
    branches:
      - main # Change this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app || mkdir ~/app && cd ~/app
            git clone git@github.com:MohanKumarMakesh/PawfectMatch.git . || git pull origin main
            npm install
            npm run build
            pm2 stop all || true
            pm2 serve build 3000 --spa --name frontend
          EOF
